easy_admin:
    
    entities:
       # List the entity class name you want to manage
        SuperUser:
            class: "App\\Entity\\SuperUser"
        Media:
            class: "App\\Entity\\Media"
            list:
                actions: ['show']
                fields:
                    - id
                    - name
                    - AddedAt
                    - { property: 'isInCarousel', label: 'Carousel'}
                    - placeCarousel
                    - { property: 'image' , type: 'image', base_path: '%app.path.media_image%'}
                    
            show:
                fields:
                    - { property: 'image' , type: 'image', base_path: '%app.path.media_image%' }
            form: 
                fields:
                    - name
                    - { property: 'imageFile', type: 'vich_image'}
                    - { property: 'isInCarousel', label: 'Carousel'}
                    - placeCarousel
        Article: 
            class: "App\\Entity\\Article"
           
    
        # design:
        #     form_theme:
        #         - '@EasyAdmin/form/bootstrap_4.html.twig'
        #         - '@VichUploader/Form/fields.html.twig'

        # config/packages/easy_admin.yaml
