vich_uploader:
    db_driver: orm

    mappings:
       media_image:
           uri_prefix: /asset/images
           upload_destination: '%kernel.project_dir%/public%app.path.media_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
