vich_uploader:
    db_driver: orm

    mappings:
       media_image:
           uri_prefix:         '%app.path.media_image%'
           upload_destination: '%kernel.project_dir%/public%app.path.media_image%'
